config = {}

config.defaultWaitTime = 500
config.TestTime = 60 -- it's multiplied by x1000 (ex: 10 =  10 seconds!)
config.TestDrivePrice = 10 -- means vehicle price / this value

config.dealerships = {
    [1] = {

        name = "Oana",
        ped = "cs_siemonyetarian",
        heading = 65.0,
        headingVehicle = 110.0,
        type = "vehicles",
        blipid = 523,

        coordsPed = vector3(-32.738410949707,-1096.3504638672,27.274339675903-1.0),
        coordsVehicle = vector3(-44.249935150146,-1097.9318847656,26.010650634766), 
        coordsCam = vector3(-47.109294891357,-1101.7886962891,26.422355651855+1.0),

        testVehicleSpawn = vector3(-19.648763656616,-1085.1463623047,27.04189491272),
        testVehicleSpawnHeading = 69.0,
        testVehicleTime = 60, -- seconds
        vehicles = {
            ["BMW"] = {
                ['BMW M760i'] = {
                    vehID = 1,
                    vip = true,
                    price        = 90000000,
                    vehicle = nil,
spawncode    = "17m760i",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M6f13'] = {
                    vehID = 2,
                    vip = true,
                    price        = 85000000,
                    vehicle = nil,
spawncode    = "m6f13",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },

                ['BMW M3f80'] = {
                    vehID = 3,
                    vip = true,
                    price        = 87000000,
                    vehicle = nil,
spawncode    = "m3f80",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M4'] = {
                    vehID = 4,
                    vip = true,
                    price        = 90000000,
                    vehicle = nil,
spawncode    = "f82",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M4 Cabrio'] = {
                    vehID = 5,
                    vip = true,
                    price        = 85000000,
                    vehicle = nil,
spawncode    = "m4c",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M5f10'] = {
                    vehID = 6,
                    vip = true,
                    price        = 80000000,
                    vehicle = nil,
spawncode    = "m516",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M3E92'] = {
                    vehID = 7,
                    vip = true,
                    price        = 70000000,
                    vehicle = nil,
spawncode    = "m3e92",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW X5'] = {
                    vehID = 8,
                    vip = true,
                    price        = 85000000,
                    vehicle = nil,
spawncode    = "48is",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M3e46'] = {
                    vehID = 9,
                    vip = true,
                    price        = 32500000,
                    vehicle = nil,
spawncode    = "e46",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW 850csi'] = {
                    vehID = 10,
                    vip = true,
                    price        = 50000000,
                    vehicle = nil,
spawncode    = "850csi",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M5e39'] = {
                    vehID = 11,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "bmwe39",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M5e28'] = {
                    vehID = 12,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "M5E28",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW M5e34'] = {
                    vehID = 13,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "e34",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW m5e60'] = {
                    vehID = 14,
                    vip = true,
                    price        = 30000000,
                    vehicle = nil,
spawncode    = "m5e60",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW E90'] = {
                    vehID = 15,
                    vip = true,
                    price        = 55000000,
                    vehicle = nil,
spawncode    = "bmwe90",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW Z3'] = {
                    vehID = 16,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "z3",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },

            ["Audi"] = {

                ['Audi R8 V10'] = {
                    vehID = 1,
                    vip = true,
                    price        = 150000000,
                    vehicle = nil,
spawncode    = "r820",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi RS7 SportBack'] = {
                    vehID = 2,
                    vip = true,
                    price        = 95000000,
                    vehicle = nil,
spawncode    = "rs7",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi RS6'] = {
                    vehID = 3,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "audirs6tk",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi A6'] = {
                    vehID = 4,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "a6avant",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi RS6'] = {
                    vehID = 5,
                    vip = true,
                    price        = 55000000,
                    vehicle = nil,
spawncode    = "rmodrs6",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi RS3 2018'] = {
                    vehID = 6,
                    vip = true,
                    price        = 67000000,
                    vehicle = nil,
spawncode    = "rs318",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi Q8 2019'] = {
                    vehID = 7,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "audiq8",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi A8 2018'] = {
                    vehID = 8,
                    vip = true,
                    price        = 60000000,
                    vehicle = nil,
spawncode    = "a8fsi",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi Quattro 1983 SE'] = {
                    vehID = 9,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "audquattros",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi S4'] = {
                    vehID = 10,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "b5s4",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi A6 2003'] = {
                    vehID = 11,
                    vip = true,
                    price        = 25000000,
                    vehicle = nil,
spawncode    = "c5rs6",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi TTRS'] = {
                    vehID = 12,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "ttrs",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi RS5 2018'] = {
                    vehID = 13,
                    vip = true,
                    price        = 85000000,
                    vehicle = nil,
spawncode    = "rs52018",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi A8 2005'] = {
                    vehID = 14,
                    vip = true,
                    price = 15000000,
                    vehicle = nil,
spawncode = "a8audi",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Audi AS7'] = {
                    vehID = 15,
                    vip = true,
                    price = 65000000,
                    vehicle = nil,
spawncode = "as7",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },

            ["Bentley"] = {
                ['Bentley SuperSport'] = {
                    vehID = 1,
                    vip = true,
                    price        = 65000000,
                    vehicle = nil,
spawncode    = "ben17",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },

            ["Ford"] = {
                ['Ford Festiva'] = {
                    vehID = 1,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "festivac",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Ford GT'] = {
                    vehID = 2,
                    vip = true,
                    price        = 25000000,
                    vehicle = nil,
spawncode    = "gt17",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Ford Mustang GT'] = {
                    vehID = 3,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "mgt",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Duba Ford'] = {
                    vehID = 4,
                    vip = true,
                    price        = 30000000,
                    vehicle = nil,
spawncode    = "e15082",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Duba Sobol'] = {
                    vehID = 5,
                    vip = true,
                    price        = 25000000,
                    vehicle = nil,
spawncode    = "sobol",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                

            },

            ["Ferrari"] = {
                ['Ferrari California'] = {
                    vehID = 1,
                    vip = true,
                    price        = 250000000,
                    vehicle = nil,
spawncode    = "fct",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Ferrari GTC Lusso'] = {
                    vehID = 2,
                    vip = true,
                    price        = 150000000,
                    vehicle = nil,
spawncode    = "gtc4",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },
            ["Mercedes Benz"] = {
                 ['"Mercedes-Benz GL63'] = {
                     vehID = 1,
                     vip = true,
                     price        = 130000000,
                     vehicle = nil,
spawncode    = "gl63",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
                 ['Mercedes-Benz E63 AMG'] = {
                     vehID = 2,
                     vip = true,
                     price        = 100000000,
                     vehicle = nil,
spawncode    = "e63amg",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
            
                 ['Mercedes-Benz C63S AMG'] = {
                     vehID = 3,
                     vip = true,
                     price        = 100000000,
                     vehicle = nil,
spawncode    = "c63s",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
            
                 ['Mercedes-Benz G-CLASS'] = {--linia 65 config
                     vehID = 4,
                     vip = true,
                     price        = 200000000,
                     vehicle = nil,
spawncode    = "g65amg",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
                 ['Mercedes-Benz S63 AMG Cabriolet'] = {
                     vehID = 5,
                     vip = true,
                     price        = 150000000,
                     vehicle = nil,
spawncode    = "mers63c",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
                 ['Mercedes-Benz GTR AMG'] = {
                     vehID = 6,
                     vip = true,
                     price        = 100000000,
                     vehicle = nil,
spawncode    = "amggtrr20",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
                 ['Mercedes-Benz Brabus 800'] = {
                     vehID = 7,
                     vip = true,
                     price        = 1700000000,
                     vehicle = nil,
spawncode    = "19S63",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
                 ['Mercedes-Benz Brabus 850'] = {
                     vehID = 8,
                     vip = true,
                     price        = 200000000,
                     vehicle = nil,
spawncode    = "brabus850",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
                 ['Mercedes-Benz C32'] = {
                     vehID = 9,
                     vip = true,
                     price        = 73000000,
                     vehicle = nil,
spawncode    = "benzc32",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
                 ['Mercedes-Benz E55'] = {
                     vehID = 10,
                     vip = true,
                     price        = 65000000,
                     vehicle = nil,
spawncode    = "benze55",
                     speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                     seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                 },
            },

            ["Lamborghini"] = {
                ['Lamborghini Aventador'] = {
                    vehID = 1,
                    vip = true,
                    price        = 300000000,
                    vehicle = nil,
spawncode    = "lamboavj",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },

                ['Lamborghini Huracan'] = {
                    vehID = 2,
                    vip = true,
                    price        = 350000000,
                    vehicle = nil,
spawncode    = "lp610",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Lamborghini Sian'] = {
                    vehID = 3,
                    vip = true,
                    price        = 250000000,
                    vehicle = nil,
spawncode    = "rmodsian",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },

            ["Nissan"] = {
                ['Nissan 370z (Drift)'] = {
                    vehID = 1,
                    vip = true,
                    price        = 65000000,
                    vehicle = nil,
spawncode    = "370z",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },



            ["Chevrolet"] = {
                ['Chevrolet Corvette C7'] = {
                    vehID = 1,
                    vip = true,
                    price        = 65000000,
                    vehicle = nil,
spawncode    = "c7",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Chevrolet G20'] = {
                    vehID = 2,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "16ss",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },

            ["Bugatti"] = {
                ['Bugatti Veyron'] = {
                    vehID = 3,
                    vip = true,
                    price        = 400000000,
                    vehicle = nil,
spawncode    = "bugatti",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Bugatti Divo'] = {
                    vehID = 4,
                    vip = true,
                    price        = 500000000,
                    vehicle = nil,
spawncode    = "divo",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },

            ["Rolls Royce"] = {
                ['Rolls Royce Cullinan'] = {
                    vehID = 1,
                    vip = true,
                    price        = 500000000,
                    vehicle = nil,
spawncode    = "cullinan",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Rolls Royce Down Onyx'] = {
                    vehID = 2,
                    vip = true,
                    price        = 400000000,
                    vehicle = nil,
spawncode    = "dawnonyx",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },
            ["Motociclete"] = {
                ['ATV Blazer'] = {
                    vehID = 1,
                    vip = true,
                    price        = 30000000,
                    vehicle = nil,
spawncode    = "blazer6",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['ATV Monster'] = {
                    vehID = 2,
                    vip = true,
                    price        = 20000000,
                    vehicle = nil,
spawncode    = "monsteratv",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['BMW S1000RR'] = {
                    vehID = 3,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "bmws",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Honda Bros'] = {
                    vehID = 4,
                    vip = true,
                    price        = 45000000,
                    vehicle = nil,
spawncode    = "bros60",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },

                ['Harley-Davidson Street'] = {
                    vehID = 5,
                    vip = true,
                    price        = 100000000,
                    vehicle = nil,
spawncode    = "hvrod",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Harley-Davidson SoftAil'] = {
                    vehID = 6,
                    vip = true,
                    price        = 100000000,
                    vehicle = nil,
spawncode    = "foxharley1",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },

                ['Harley-Davidson Touring'] = {
                    vehID = 7,
                    vip = true,
                    price        = 100000000,
                    vehicle = nil,
spawncode    = "foxharley2",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },

                ['SXF450'] = {
                    vehID = 8,
                    vip = true,
                    price        = 25000000,
                    vehicle = nil,
spawncode    = "ktmsm",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },

                ['Yamaha R1'] = {
                    vehID = 9,
                    vip = true,
                    price        = 37000000,
                    vehicle = nil,
spawncode    = "r1",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Yamaha R1-2020'] = {
                    vehID = 10,
                    vip = true,
                    price        = 40000000,
                    vehicle = nil,
spawncode    = "20r1",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Yamaha R6'] = {
                    vehID = 11,
                    vip = true,
                    price        = 65000000,
                    vehicle = nil,
spawncode    = "r6",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Yamaha TMax'] = {
                    vehID = 12,
                    vip = true,
                    price        = 15000000,
                    vehicle = nil,
spawncode    = "tmaxDX",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },
            ["Range Rover"] = {
                ['Range Rover Vogue'] = {
                    vehID = 1,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "rrst",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Range Rover Sport'] = {
                    vehID = 2,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "rrs08",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },

            },
        
            ["Toyota"] = {

                ['Toyota Supra CeliSupra'] = {
                    vehID = 1,
                    vip = true,
                    price        = 100000000,
                    vehicle = nil,
spawncode    = "celisupra",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },

            ["Masini Cayo"] = {

                ['Sanchez'] = {
                    vehID = 1,
                    vip = true,
                    price        = 30000000,
                    vehicle = nil,
spawncode    = "sanchez",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Buggy'] = {
                    vehID = 2,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "dune",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Cayo Runner'] = {
                    vehID = 3,
                    vip = true,
                    price        = 25000000,
                    vehicle = nil,
spawncode    = "bodhi2",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Buggy 2'] = {
                    vehID = 4,
                    vip = true,
                    price        = 34000000,
                    vehicle = nil,
spawncode    = "bifta",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Buggy 3'] = {
                    vehID = 5,
                    vip = true,
                    price        = 34000000,
                    vehicle = nil,
spawncode    = "bfinjection",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },

            ["Dube"] = {

                ['Duba Speedo'] = {
                    vehID = 1,
                    vip = true,
                    price        = 37000000,
                    vehicle = nil,
spawncode    = "nspeedo",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },
            ["Altele"] = {
                ['Honda S2000'] = {
                    vehID = 1,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "ap2",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Honda NSX 1990'] = {
                    vehID = 2,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "na1",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Tesla Model S'] = {
                    vehID = 3,
                    vip = true,
                    price        = 90000000,
                    vehicle = nil,
spawncode    = "models",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Volkswagen Golf 7 GTI'] = {
                    vehID = 4,
                    vip = true,
                    price        = 70000000,
                    vehicle = nil,
spawncode    = "golf7gti",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Volkswagen Tiguan'] = {
                    vehID = 5,
                    vip = true,
                    price        = 60000000,
                    vehicle = nil,
spawncode    = "taigun21",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Volkswagen Golf 2'] = {
                    vehID = 6,
                    vip = true,
                    price        = 30000000,
                    vehicle = nil,
spawncode    = "golf2",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Tesla Model 3'] = {
                    vehID = 7,
                    vip = true,
                    price        = 75000000,
                    vehicle = nil,
spawncode    = "tmodel",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Cadillac CTSV'] = {
                    vehID = 8,
                    vip = true,
                    price        = 40000000,
                    vehicle = nil,
spawncode    = "ctsv16",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Cadillac XCL Limo'] = {
                    vehID = 9,
                    vip = true,
                    price        = 55000000,
                    vehicle = nil,
spawncode    = "limoxts",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                
                ['Dodge Charger'] = {
                    vehID = 10,
                    vip = true,
                    price        =  78000000,
                    vehicle = nil,
spawncode    = "16charger",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Dodge Challenger'] = {
                    vehID = 11,
                    vip = true,
                    price        = 78000000,
                    vehicle = nil,
spawncode    = "16challenger",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },

                ['Subaru BRZ'] = {
                    vehID = 12,
                    vip = true,
                    price        = 45000000,
                    vehicle = nil,
spawncode    = "brz13",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Subaru VRX STI'] = {
                    vehID = 13,
                    vip = true,
                    price        = 45000000,
                    vehicle = nil,
spawncode    = "subisti08",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Subaru BRZ'] = {
                    vehID = 14,
                    vip = true,
                    price        = 25000000,
                    vehicle = nil,
spawncode    = "brztuning",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['MClaren MP4'] = {
                    vehID = 15,
                    vip = true,
                    price        = 300000000,
                    vehicle = nil,
spawncode    = "mp412c",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['PaganiHuayra RoadSter'] = {
                    vehID = 16,
                    vip = true,
                    price        = 55000000,
                    vehicle = nil,
spawncode    = "rmodpagani",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Porsche 911TurboS'] = {
                    vehID = 17,
                    vip = true,
                    price        = 80000000,
                    vehicle = nil,
spawncode    = "911turboS",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Volkswagen Toureg R50'] = {
                    vehID = 18,
                    vip = true,
                    price        = 55000000,
                    vehicle = nil,
spawncode    = "r50",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Quartz Regalia'] = {
                    vehID = 19,
                    vip = true,
                    price        = 65000000,
                    vehicle = nil,
spawncode    = "regalia",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Can-Am Maverick X3'] = {
                    vehID = 20,
                    vip = true,
                    price        = 55000000,
                    vehicle = nil,
spawncode    = "can",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Porsche Macan Turbo'] = {
                    vehID = 21,
                    vip = true,
                    price        = 420000000,
                    vehicle = nil,
spawncode    = "18macan",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['GMC Denali'] = {
                    vehID = 22,
                    vip = true,
                    price        = 45000000,
                    vehicle = nil,
spawncode    = "denalihd",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Jeep Hawk'] = {
                    vehID = 23,
                    vip = true,
                    price        = 95000000,
                    vehicle = nil,
spawncode    = "rmodjeep",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Jeep Wrangler Rubicon'] = {
                    vehID = 24,
                    vip = true,
                    price        = 85000000,
                    vehicle = nil,
spawncode    = "jp12",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Jeep Gladiator'] = {
                    vehID = 25,
                    vip = true,
                    price        = 85000000,
                    vehicle = nil,
spawncode    = "jeepg",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Dacia Logan 2021'] = {
                    vehID = 26,
                    vip = true,
                    price        = 20000000,
                    vehicle = nil,
spawncode    = "logan21",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Dacia Logan'] = {
                    vehID = 27,
                    vip = true,
                    price        = 20000000,
                    vehicle = nil,
spawncode    = "logan",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Dacia Duster'] = {
                    vehID = 28,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "daduster",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Dacia Sandero'] = {
                    vehID = 29,
                    vip = true,
                    price        = 35000000,
                    vehicle = nil,
spawncode    = "sandero",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Dacia Sandero Stepway'] = {
                    vehID = 30,
                    vip = true,
                    price        = 30000000,
                    vehicle = nil,
spawncode    = "sanderos2",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Mazda MX-5 Miata'] = {
                    vehID = 31,
                    vip = true,
                    price        = 65000000,
                    vehicle = nil,
spawncode    = "na6",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Opel Rekord'] = {
                    vehID = 32,
                    vip = true,
                    price        = 15000000,
                    vehicle = nil,
spawncode    = "2dopelr3",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Peugeot 206'] = {
                    vehID = 33,
                    vip = true,
                    price        = 15000000,
                    vehicle = nil,
spawncode    = "206c",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
                ['Volvo V242'] = {
                    vehID = 34,
                    vip = true,
                    price        = 15000000,
                    vehicle = nil,
spawncode    = "v242",
                    speed        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    acceleration = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    brakes       = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                    seats        = {barsize = 100, text = "nu conteaza, e perversa rau"}, 
                },
            },
        }
    }
}

config.openSHmsg = "~w~Apasa ~INPUT_CONTEXT~ pentru a accesa masinile"