local cfg = {}

cfg.items = {
  	["seeds"] = {"Seeds", "Niste seminte de iarba.", nil, 0.1,"pocket"},
  	["credit"] = {"Card-uri de Credit Furate", "Card-uri de Credit furate care pot fi transformate in Buletine Ilegale la Falsificator.", nil, 0.2,"pocket"},
  	["bank_money"] = {"Bani de Banca", "$.", nil, 0,"pocket"},
  	["trash"] = {"Gunoi", "Pute a hoit!", nil, 0,"pocket"},
  	["fake_id"] = {"Buletin Falsificat", "Scrie un nume pe el Hmmm...", nil, 0,"pocket"},
	["cigarette"] = {"Tigara cu Ciuperci","Tigari cu ciuperci pentru viata usoara.", nil,0.1,"pocket"},
	["AK47"] = {"AK47", "Un masterpeice de Rusia.", nil, 0.4,"pocket"},
	["DB"] = {"Deagle", "Deagle", nil, 0.4,"pocket"},
	["M4A1"] = {"M4A1", "Un masterpiece de America.", nil, 0.4,"pocket"},
	["peste"] = {"Peste", "Peste mic gasit in mare", nil, 1.0},
	["rinichi"] = {"Rinichi", "", nil, 0.4,"pocket"},
	["inima"] = {"Inima", "", nil, 0.4,"pocket"},
	["ficat"] = {"Ficat", "", nil, 1.0},
	["foita"] = {"Foita", "", nil, 0.1},
	["tutun"] = {"Tutun", "", nil, 0.1},
	["tigara"] = {"Tigari Contrabanda", "", nil, 0.1},
	["ciuperca"] = {"Ciuperci", "Ciuperca pentru vanzare..", nil, 1.0},
	["carne"] = {"Carne", "Carne de vanzare. [Vacar]", nil, 1.0},
	["oilcan"] = {"Canistra de ulei", "Deseu", nil, 0},
	["shoe"] = {"Cizma", "O fi cizma lui Jack Sparrow?", nil, 0},
	["secure_card"] = {"Card de Securitate", "Acest card se foloseste pentru jafuri", nil, 1.0},
	["cashbag"] = {"Punga cu bani uzi", "Ce idiot", nil, 0},
	["asigurare"] = {"Asigurare", "Asigurare Auto", nil, 0},
	["fishingrod"] = {"Undita", "Foloseste-o numai pe malul apei", nil, 0.01},
	["momealapeste"] = {"Momeala", "Ar trebui sa prinda ceva", nil, 0.01},
	["foarfece"] = {"Foarfece", "Foarfeca pentru jobul de ciupercar", nil, 0.01},
	["zaruri_norocuase"] = {"Zaruri", "Zaruri de categoria grea", nil, 0.01},
	["radio"] = {"Radio", "Statie Radio", nil, 0.5},
	["Permis"] = {"Permis de conducere", "Permis de conducere", nil, 0},
	---- AICI AM RAMAS CU ICONITELE -------  
	["minereudiamant"] = {"Minereu Diamant", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereusulf"] = {"Minereu Sulf", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereuaur"] = {"Minereu Aur", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereucarbune"] = {"Minereu Carbune", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereuargint"] = {"Minereu Argint", "Pentru jobul de miner", nil, 0,"pocket"},
	["minereufier"] = {"Minereu Fier", "Pentru jobul de miner", nil, 0,"pocket"},
	["inelcudiamant"] = {"Inel cu Diamant", "Pentru jobul de miner", nil, 0,"pocket"},
	["conserva"] = {"Conserva", "Pentru jobul de miner", nil, 0,"pocket"},
	["pickaxe"] = {"Pickaxe", "Pentru jobul de miner", nil, 0,"pocket"},
	["plastic"] = {"Plastic", "Pentru jobul de miner", nil, 0,"pocket"},
	["tank"] = {"Minereu", "Pentru jobul de miner", nil, 0,"pocket"},
	["picamer"] = {"Picamer", "Picamer pentru constructor", nil, 0,"pocket"},
	["ciocan"] = {"Ciocan", "Ciocan pentru jobul de constructor", nil, 0,"pocket"},
	["lighter"] = {"Bricheta", "O bricheta tip vintage",nil,0.5,"pocket"},
	["gold_bar"] = {"Lingou de Aur", "Un lingou de aur pur!",nil,0,"pocket"},
	["lockpick_tools"] = {"Unelte Incuietori", "Unelte pentru a sparge incuietorile usilor.", nil, 0.2,"pocket"},
	["trusa"] = {"Trusa","Obiecte preferate pentru minerit",nil,0.4,"pocket"},
	["pet"] = {"Sticla Goala","Bun pentru depozitare bauturi!",nil,0.1,"pocket"},
	["aphone"] = {"Telefon Mobil", "Call and send SMS.", nil, 0,"pocket"},
	["photosm"] = {"Poza Mixta","Poza cu cu peisaj urban si natural combinat!",nil,0.1,"pocket"},
	["samanta"] = {"Samanta de rosie","Gustul bun de rosie vine de la o samanta buna!",nil,0.1,"pocket"},
	["revista"] = {"Revista Natura","O revista incantatoare care ajuta oameni sa se relaxeze citindo!",nil,0.1,"pocket"},
	["ziar"] = {"Ziar","Un ziar care aduce multe stiri societatii!",nil,0.1,"pocket"},
	["fier"] = {"Fier","Minereu de fier",nil,0.0,"pocket"},
	["cupru"] = {"Cupru","Cupru",nil,0.0,"pocket"},
	["sulf"] = {"Sulf","Sulf",nil,0.0,"pocket"},
	["prafdepusca"] = {"Praf de Pusca","Praf de Pusca",nil,0.0,"pocket"},
	["amethyst"] = {"Amethyst","Piatra pretioasa",nil,0.6,"pocket"},
	["safir"] = {"Safir","Piatra foarte pretioasa",nil,0.6,"pocket"},
	["uranium"] = {"Uranium","Radioactivitatea ei creaza haos",nil,0.6,"pocket"},
	["aur"] = {"Aur","Metal Pretios foarte valoros",nil,0.6,"pocket"},
	["diamant"] = {"Diamant","Diamant foarte pretios si foarte valoros, INDESTRUCTIBIL",nil,0.6,"pocket"},
	["id_doc"] = {"Buletin","Un buletin cu numele si informatiile tale pe el! Nu il pierde",nil,0,"pocket"},
	["gunpermit_doc"] = {"Permis Port-Arma","Un permis ce te lasa sa ai asupra ta arme de foc",nil,0,"pocket"},
	["hash_token_rocketcasino"] = {"Moneda Cazino","Moneda cu care poti juca la cazino",nil,0,"pocket"},
	["asigurare_masina"] = {"Asigurare de Masina","O Asigurare de masina pe care o puteti oferi la altii sau pastra pentru masina voastra",nil,0,"pocket"},
	["dosardmv"] = {"Dosar DMV","Cu acest item te duci la un politist pentru a da de permis, el te va verifica daca ai dosar sau nu.",nil,0,"pocket"},
	["thermal_charge"] = {"Thermal", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["laptop_h"] = {"Laptop", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["lockpick"] = {"Lockpick", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["id_card"] = {"Id Card", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
	["bijuterii"] = {"Bijuterii pretioase","",nil,0.2},
	["combomeal"] = {"Combo Meal", "Mc Donalds",nil,0.8,"pocket"},
	["bigmac"] = {"Big Mac", "Mc Donalds",nil,0.8,"pocket"},
	["mcpollo"] = {"Mc pollo", "Mc Donalds",nil,0.8,"pocket"},
	["mcroyaldeluxe"] = {"Royal Deluxe ", "Mc Donalds",nil,0.8,"pocket"},
	["cbo"] = {"CBO", "Mc Donalds",nil,0.8,"pocket"},
	["cuartodelibra"] = {"Cuarto de Libra", "Mc Donalds",nil,0.8,"pocket"},
	["grandmcextreme"] = {"Grand McExtreme Bacon Burger", "Mc Donalds",nil,0.8,"pocket"},
	["bigchickensupreme"] = {"Big Chicken Supreme", "Mc Donalds",nil,0.8,"pocket"},
	["bigcrispybbq"] = {"Big Crispy BBQ", "Mc Donalds",nil,0.8,"pocket"},
	["bigdoublecheese"] = {"Big Double Cheese", "Mc Donalds",nil,0.8,"pocket"},
	["hamburgesa"] = {"Hamburger", "Mc Donalds",nil,0.8,"pocket"},
	["cristalcocaina"] = {"Cristal Cocaina", "Cristale ilegale",nil,0.5,"pocket"},
    ["cristalheroina"] = {"Cristal Heroina", "Cristale ilegale",nil,0.7,"pocket"},
	["drug_cansativa"] = {"Cannabis Sativa", "Esenta de canabis folosita pentru crearea drogurilor puternice",nil,0.5,"pocket"},
	["drug_cocaalka"] = {"Cocaina Alkaloid", "Un lighid albastru extras din planta coca",nil,0.7,"pocket"},
	["drug_unprocpcp"] = {"PCP Neprocesat", "Praf alb de PCP neprocesat",nil,0.6,"pocket"},
	["drug_lyseracid"] = {"Acid Lysergic", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.8,"pocket"},
    ["iarba"] = {"Cristal Heroina", "Cristale ilegale",nil,0.5,"pocket"},
    ["stack_iarba"] = {"Cannabis Sativa", "Esenta de canabis folosita pentru crearea drogurilor puternice",nil,4,"pocket"},
    ["cocaina"] = {"Cocaina Alkaloid", "Un lighid albastru extras din planta coca",nil,0.5,"pocket"},
    ["stack_cocaina"] = {"PCP Neprocesat", "Praf alb de PCP neprocesat",nil,4,"pocket"},
    ["metanfetamina"] = {"Acid Lysergic", "Substanta puternica din seminte de Turbina Corymbosa",nil,0.5,"pocket"},
    ["stack_metanfetamina"] = {"Acid Lysergic", "Substanta puternica din seminte de Turbina Corymbosa",nil,4,"pocket"},
	["hamburgesadepollo"] = {"Hamburger pollo", "Mc Donalds",nil,0.8,"pocket"},
	["mcfish"] = {"Mc Fish", "Mc Donalds",nil,0.8,"pocket"},
	["happymeal"] = {"Happy Meal", "Mc Donalds",nil,0.8,"pocket"},
	["cocacola"] = {"Coca Cola", "Mc Donalds",nil,0.8,"pocket"},
	["nestea"] = {"Nestea", "Mc Donalds",nil,0.8,"pocket"},
	["agua"] = {"Apa", "Mc Donalds",nil,0.8,"pocket"},
	["monsterenergy"] = {"Monster Energy", "Mc Donalds",nil,0.8,"pocket"},
	["aquarius"] = {"Apa", "Mc Donalds",nil,0.8,"pocket"},
	["cerveza"] = {"Cerveza", "Mc Donalds",nil,0.8,"pocket"},
	["sprite"] = {"Sprite", "Mc Donalds",nil,0.8,"pocket"},
	["nuggets"] = {"Nuggets", "Mc Donalds",nil,0.8,"pocket"},
	["patatasfritas"] = {"Cartofi", "Mc Donalds",nil,0.8,"pocket"},
	["topfries"] = {"Top Fries", "Mc Donalds",nil,0.8,"pocket"},
	["fanta"] = {"Fanta", "Mc Donalds",nil,0.8,"pocket"},
	["harness"] = {"Harness", "Niste Lysergsäurediethylamid cultivata.", nil, 0.1,"pocket"},
   ["cargo"] = {"Colete Cargo", "Cutii pline cu porno + BRAZZERS Premium.", nil, 0,"pocket"},
   ["filter"] = {"Filtru","Filtru pentru ciuperci de tigara.", nil,0.2,"pocket"},
   ["foitasall"] = {"Foita", "", nil, 0.1},
   ["tutunsall"] = {"Tutun", "", nil, 0.1}, 
   ["tigarasall"] = {"Tigara", "", nil, 0.15},
   ["pachet"] = {"Pachet de Tigari", "", nil, 0.2},
   ["cartus"] = {"Cartus de Tigari", "", nil, 0.3},   
   ["dirty_money"] = {"Bani Murdari", "Buni murdari de la jaf", nil, 0,"pocket"},
   ["key_lspd"] = {"Cheie Sectie","O cheie pentru sectia de politie",nil,0,"key"},
   ["tabac"] = {"Tabac", "Pentru jobul de Trabucuri", nil, 0,"pocket"},
   ["filtru"] = {"Filtru", "Pentru jobul de Trabucuri", nil, 0,"pocket"},
   ["trabuc"] = {"Trabuc", "Pentru jobul de Trabucuri", nil, 0,"pocket"},
   ["drug_salvia"] = {"Salvia Divinorum", "Frunze din planta Salvia Divinorum cu efecte Halucinogene dezastruase.",nil,0.5,"pocket"},
   ["drug_datura"] = {"Datura", "Seminte de Ciumafaia toxice pentru consumul uman. ",nil,0.7,"pocket"},
   ["drug_mushroom"] = {"Ciuperca", "Ciupercoase halucinogene",nil,0.6,"pocket"},
   ["drug_canindica"] = {"Canabis Indica", "Canabis cu efecte de somnolenta.",nil,0,"pocket"},
	---["aphone"] = {"Telefon Mobil", "Call and send SMS.", nil, 0,"pocket"},
   ["permisarma"] = {"Permis Arma","Cu acest item ai voie sa porti arme de calibru mediu dupa tine.",nil,0,"pocket"},
   ["drug_cocaleaves"] = {"Frunze Coca", "Frunze de coca folosite pentru prepararea cocainei.",nil,0.8},
   ["jewelry"] = {"Bijuterii","Bijuterii Valoroase",nil,0.1,"pocket"},
   ["Pachet Secret"] = {"Pachet Secretos", "AmogUs",nil,0.0,"pocket"},
   -- owned by dumnezeu

	----------------ROLEPLAY
	["Pessos"] = {"Pessos","",nil,0.02,"pocket"},
	----ADVANCED VEHICLES---
	["scanner"] = {"Scanner", "", nil, 0},
	['oil'] = {'Engine oil', "", nil, 0},
	['tires'] = {'Tires', "", nil, 0},
	['brake_pads'] = {'Brake pads', "", nil, 0},
	['transmission_oil'] = {'Transmission oil', "", nil, 0},
	['shock_absorber'] = {'Shock absorber', "", nil, 0},
	['clutch'] = {'Clutch', "", nil, 0},
	['air_filter'] = {'Air filter', "", nil, 0},
	['fuel_filter'] = {'Fuel filter', "", nil, 0},
	['spark_plugs'] = {'Spark plugs', "", nil, 0},
	['serpentine_belt'] = {'Serpentine belt', "", nil, 0},
	['susp'] = {'Lowered suspension', "", nil, 0},
	['susp1'] = {'Stanced suspension', "", nil, 0},
	['susp2'] = {'Sport suspension', "", nil, 0},
	['susp3'] = {'Confort suspension', "", nil, 0},
	['susp4'] = {'Lifted suspension', "", nil, 0},
	['garett'] = {'Garett GTW Turbo', "", nil, 0},
	['nitrous'] = {'Nitro', "", nil, 0},
	['AWD'] = {'AWD swap', "", nil, 0},
	['RWD'] = {'RWD swap', "", nil, 0},
	['FWD'] = {'FWD swap', "", nil, 0},
	['semislick'] = {'Semi Slick tires', "", nil, 0},
	['slick'] = {'Slick tires', "", nil, 0},
	['race_brakes'] = {'Brembo brakes', "", nil, 0},
	['piston'] = {'Piston', "", nil, 0},
	['rod'] = {'Rod', "", nil, 0},
	['gear'] = {'Gear', "", nil, 0},
	['brake_discs'] = {'Brake disc', "", nil, 0},
	['brake_caliper'] = {'Brake caliper', "", nil, 0},
	['springs'] = {'Springs', "", nil, 0},
	['iron'] = {'Iron', "", nil, 0},
	['aluminum'] = {'Aluminum', "", nil, 0},

	------------------------------------------ MINER ------------------------------------------------------------
	["diamant"]              = {"Diamant",              "Diamant",                       nil, 1.00, "pocket"},
	["aur"]                  = {"Aur",                  "Aur",                           nil, 0.50, "pocket"},
	["argint"]               = {"Argint",               "Argint",                        nil, 0.50, "pocket"},
	["fier"]                 = {"Fier",                 "Fier",                          nil, 0.40, "pocket"},
	["carbune"]              = {"Carbune",              "Carbune",                       nil, 0.30, "pocket"},
	["piatra"]               = {"Piatra",               "Piatra",                        nil, 0.20, "pocket"},
	["sulf"]                 = {"Sulf",                 "Sulf",                          nil, 0.50, "pocket"},
	["prafdepusca"]          = {"Praf de pusca",        "Praf de pusca",                 nil, 0.10, "pocket"},
	["srapnel"]              = {"Srapnel",              "Srapnel",                       nil, 0.10, "pocket"},
	["minereudiamant"]       = {"Minereu Diamant",      "Minereu Diamant",               nil, 1.00, "pocket"},
	["minereuaur"]           = {"Minereu Aur",          "Minereu Aur",                   nil, 0.50, "pocket"},
	["minereuargint"]        = {"Minereu Argint",       "Minereu Argint",                nil, 0.50, "pocket"},
	["minereufier"]          = {"Minereu Fier",         "Minereu Fier",                  nil, 0.30, "pocket"},
	["minereucarbune"]       = {"Minereu Carbune",      "Minereu Carbune",               nil, 0.30, "pocket"},
	["minereupiatra"]        = {"Minereu Piatra",       "Minereu Piatra",                nil, 0.20, "pocket"},
	["minereusulf"]          = {"Minereu Sulf",         "Minereu Sulf",                  nil, 0.50, "pocket"},
	["pickaxe"]              = {"Pickaxe",              "Pickaxe",                       nil, 1.00, "pocket"}, 
	------------------------------------------ PESCAR ----------------------------------------------------------
	["momealapeste"]         = {"Momeala",              "Ar trebui sa prinda ceva",      nil, 0.10, "pocket"},
	["momeala"]              = {"Momeala",              "Ar trebui sa prinda ceva",      nil, 0.10, "pocket"},
	["undita"]               = {"Undita",               "Ar trebui sa prinda ceva",      nil, 0.01, "common"},
	["peste"]                = {"Platica",              "Peste mic gasit in mare",       nil, 0.50, "pocket"},
	["peste1"]               = {"Delfin",               "Delfin",                        nil, 0.50, "pocket"},
	["peste2"]               = {"Rechin",               "Rechin d-ala de musca",         nil, 0.50, "pocket"},
	["peste3"]               = {"Peste de Germania",    "Peste de Germania",             nil, 1.00, "pocket"},
	["Dorada"]               = {"Dorada",               "Dorada",                        nil, 0.50, "pocket"},
	["Scrumbie"]             = {"Scrumbie",             "Scrumbie",                      nil, 0.50, "pocket"},
	["Merluciu"]             = {"Merluciu",             "Merluciu",                      nil, 0.50, "pocket"},
	["Calcan"]               = {"Calcan",               "Calcan",                        nil, 0.50, "pocket"},
	["Barracuda"]            = {"Barracuda",            "Barracuda",                     nil, 0.50, "pocket"},
	["Nisetru"]              = {"Nisetru",              "Nisetru",                       nil, 0.50, "pocket"},
	["Anghila"]              = {"Anghila",              "Anghila",                       nil, 0.50, "pocket"},
	["Tipar"]                = {"Tipar",                "Tipar",                         nil, 1.00, "pocket"},
	["Piranha"]              = {"Piranha",              "Piranha",                       nil, 1.00, "pocket"},
	["Spada"]                = {"Spada",                "Spada",                         nil, 1.00, "pocket"},
	["Ton"]                  = {"Ton",                  "Ton",                           nil, 0.50, "pocket"},
	["Rechin"]               = {"Rechin",               "Rechin",                        nil, 2.00, "pocket"},
	------------------------------------------ PESCAR LARG -----------------------------------------------------
	["oilcan"]               = {"Canistra de ulei",     "Deseu",                         nil, 0.01, "pocket"},
	["shoe"]                 = {"Cizma",                "O fi cizma lui Jack Sparrow?",  nil, 0.01, "pocket"},
	["cashbag"]              = {"Punga cu bani uzi",    "Ce idiot",                      nil, 0.01, "pocket"},
	["fishingrod"]           = {"Undita",               "Foloseste-o pe malul apei",     nil, 0.01, "pocket"},
	------------------------------------------ CIUPERCAR -------------------------------------------------------
	["ciuperca"]             = {"Ciuperca",             "Ciuperca",                      nil, 0.50, "pocket"},
	["foarfece"]             = {"Foarfece",             "Foarfece",                      nil, 2.00, "pocket"},
	------------------------------------------ Constructor -----------------------------------------------------
	["picamer"]              = {"Picamer",              "Picamer pentru constructor",    nil, 3.00, "pocket"},
	------------------------------------------ Santierist ------------------------------------------------------
	["ciocan"]               = {"Ciocan",               "Ciocan pentru santierist",      nil, 3.00, "pocket"},
	------------------------------------------ CURIER ----------------------------------------------------------
	["colete"]               = {"Colete",               "Colete",                        nil, 0.50, "pocket"},
	------------------------------------------ CURIER MANCARE --------------------------------------------------
	["meniunoodles"]         = {"Meniu Noodles",        "Meniu Noodles",                 nil, 0.30, "pocket"},
	["meniuburger"]          = {"Meniu Burger",         "Meniu Burger",                  nil, 0.30, "pocket"},
	["meniupizza"]           = {"Meniu Pizza",          "Meniu Pizza",                   nil, 0.30, "pocket"},
	["meniucrispy"]          = {"Meniu Crispy",         "Meniu Crispy",                  nil, 0.30, "pocket"},
	------------------------------------------ PIZZA BOY -------------------------------------------------------
	["pizza"]                = {"Pizza",                "Pizza",                         nil, 0.50, "pocket"},
	------------------------------------------ PETROLIST -------------------------------------------------------
	["petrol"]               = {"Petrol",               "De prelucrat",                  nil, 0.50, "pocket"},
	["combustibil"]          = {"Combustibil",          "De prelucrat",                  nil, 0.50, "pocket"},
	------------------------------------------ Brutar ----------------------------------------------------------
	["franzela"]             = {"Franzela",             "Franzela",                      nil, 0.20, "pocket"},
	["bagheta"]              = {"Bagheta",              "Bagheta",                       nil, 0.20, "pocket"},
	["focaccia"]             = {"Focaccia",             "Focaccia",                      nil, 0.20, "pocket"},
	["lipie"]                = {"Lipie",                "Lipie",                         nil, 0.20, "pocket"},
	["croissant"]            = {"Croissant",            "Croissant",                     nil, 0.20, "pocket"},
	["covrig"]               = {"Covrig",               "Covrig",                        nil, 0.20, "pocket"},
	["faina"]                = {"Faina",                "Faina",                         nil, 0.20, "pocket"},
	------------------------------------------ DRUG ------------------------------------------------------------
	["dirtymoney"]           = {"Bani murdari",         "Bani murdari",                  nil,    0, "pocket"},
	["bricheta"]             = {"Bricheta",             "Bricheta",                      nil, 0.10, "pocket"},
	["fitil"]                = {"fitil",                "fitil",                         nil, 0.10, "pocket"},
	["coca"]                 = {"coca",                 "coca",                          nil, 0.20, "pocket"},
	["cocaine"]              = {"Cocaina",              "Cocaine",                       nil, 0.10, "pocket"},
	["pachetcocaina"]        = {"Ziplock",              "Ziplock",                       nil, 0.10, "pocket"},
	["sativaleaf"]           = {"Sativa",               "Sativa",                        nil, 0.20, "pocket"},
	["morfine"]              = {"Morfina",              "Morfina",                       nil, 0.20, "pocket"},
	["heroine"]              = {"Heroina",              "Heroina",                       nil, 0.50, "pocket"},
	["seringa"]              = {"Seringa",              "Seringa",                       nil, 0.10, "pocket"}, 
	["anhiridaacetica"]      = {"Anhirida Acetica",     "Anhirida Acetica",              nil, 0.10, "pocket"},
	["colorantrosu"]         = {"Colorant Rosu",        "Colorant Rosu",                 nil, 0.10, "pocket"},
	["colorantroz"]          = {"Colorant Roz",         "Colorant Roz",                  nil, 0.10, "pocket"},
	["colorantmov"]          = {"Colorant Mov",         "Colorant Mov",                  nil, 0.10, "pocket"},
	["colorantmaro"]         = {"Colorant Maro",        "Colorant Maro",                 nil, 0.10, "pocket"},
	["colorantgalben"]       = {"Colorant Galben",      "Colorant Galben",               nil, 0.10, "pocket"},
	["colorantalbastru"]     = {"Colorant Albastru",    "Colorant Albastru",             nil, 0.10, "pocket"},
	["purplehaze"]           = {"Purple Haze",          "Purple Haze",                   nil, 0.30, "pocket"},
	["chocolatehaze"]        = {"Chocolate Haze",       "Chocolate Haze",                nil, 0.30, "pocket"},
	["goldenhaze"]           = {"Golden Haze",          "Golden Haze",                   nil, 0.30, "pocket"},
	["hazeberry"]            = {"Haze Berry",           "Haze Berry",                    nil, 0.30, "pocket"},
	["superlemonhaze"]       = {"Super Lemon Haze",     "Super Lemon Haze",              nil, 0.30, "pocket"},
	["strawberryhaze"]       = {"Strawberry Haze",      "Strawberry Haze",               nil, 0.30, "pocket"},
	["raspberryhaze"]        = {"Raspberry Haze",       "Raspberry Haze",                nil, 0.30, "pocket"},
	["coacaze"]              = {"Coacaze",              "Coacaze",                       nil, 0.10, "pocket"},
	["capsuni"]              = {"Capsuni",              "Capsuni",                       nil, 0.10, "pocket"},
	["zmeura"]               = {"Zmeura",               "Zmeura",                        nil, 0.10, "pocket"},
	["ciocolata"]            = {"Ciocolata",            "Ciocolata",                     nil, 0.10, "pocket"},
	["marauriu"]             = {"Mar Auriu",            "Mar Auriu",                     nil, 0.10, "pocket"},
	["lamaie"]               = {"Lamaie",               "Lamaie",                        nil, 0.10, "pocket"}, 
	["afine"]                = {"Afine",                "Afine",                         nil, 0.10, "pocket"}, 
	["drug_seeds"]           = {"Seminte",              "Seminte",                       nil, 0.10, "pocket"}, 
	------------------------------------------ TRAFICANT TIGARI ------------------------------------------------
	["filtru"]   		     = {"Filtru",                "Filtru",                       nil, 0.10, "pocket"}, 
	["foita"]   		     = {"Foita",                 "Foita",                        nil, 0.10, "pocket"}, 
	["tutun"]   		     = {"Tutun",                 "Tutun",                        nil, 0.20, "pocket"}, 
	["tigara"]   		     = {"Tigara",                "Tigara",                       nil, 0.20, "pocket"}, 
	["pachet"]   		     = {"Pachet de tigari",      "Pachet de tigari",             nil, 0.30, "pocket"}, 
	["cartus"]               = {"Cartus de tigari",      "Cartus de tigari",             nil, 0.50, "pocket"}, 
	["trabuc"]               = {"Trabuc",                "Trabuc",                       nil, 0.50, "pocket"}, 
	["pachettrabuc"]         = {"Pachet de trabucuri",   "Pachet de trabucuri",          nil, 0.50, "pocket"},
	------------------------------------------ TRAFICANT ALCOOL ------------------------------------------------
	["sticlagoala"]          = {"Sticla Goala",          "Sticla Goala",                 nil, 0.01, "pocket"}, 
	["alcool"]               = {"Alcool",                "Alcool",                       nil, 0.01, "pocket"}, 
	["vinjob"]               = {"Sticla de vin",         "Sticla de vin",                nil, 0.01, "pocket"}, 
	["whiskeyjob"]           = {"Sticla de whiskey",     "Sticla de whiskey",            nil, 0.01, "pocket"}, 
	["vodkajob"]             = {"Sticla de vodka",       "Sticla de vodka",              nil, 0.01, "pocket"}, 
	["tuicajob"]             = {"Sticla de tuica",       "Sticla de tuica",              nil, 0.01, "pocket"}, 
	["romjob"]               = {"Sticla de rom",         "Sticla de rom",                nil, 0.01, "pocket"}, 
	------------------------------------------ TRAFICANT ETNOBOTANICE ------------------------------------------
	["prafdecopt"]           = {"Praf de copt",          "Praf de copt",                 nil, 0.10, "pocket"}, 
	["otravadesobolani"]     = {"Otrava de sobolani",    "Otrava de sobolani",           nil, 0.10, "pocket"}, 
	["ingrasamant"]          = {"Ingrasamant",           "Ingrasamant",                  nil, 0.10, "pocket"}, 
	["acetona"]   	      	 = {"Acetona",               "Acetona",                      nil, 0.10, "pocket"}, 
	["ciupercihalucinogene"] = {"Ciuperci Halucinogene", "Ciuperci Halucinogene",        nil, 0.30, "pocket"}, 
	["cocaina"]              = {"Cocaina",               "Cocaina",                      nil, 0.30, "pocket"}, 
	["crack"]                = {"Crack",                 "Crack",                        nil, 0.30, "pocket"}, 
	["ecstasy"]              = {"Ecstasy",               "Ecstasy",                      nil, 0.30, "pocket"}, 
	["LSD"]                  = {"LSD",                   "LSD",                          nil, 0.30, "pocket"}, 
	------------------------------------------ LICENTE --------------------------------------------------------
	["taxi_licenta"]         = {"Licenta Taxi",          "Licenta Taxi",                 nil, 0.01, "pocket"},
	["mecanic_licenta"]      = {"Licenta Mecanic",       "Licenta Mecanic",              nil, 0.01, "pocket"},
	["miner_licenta"]        = {"Licenta Miner",         "Licenta Miner",                nil, 0.01, "pocket"},
	["pilot_licenta"]        = {"Licenta Pilot",         "Licenta Pilot",                nil, 0.01, "pocket"},
	["trucker_licenta"]      = {"Licenta Trucker",       "Licenta Trucker",              nil, 0.01, "pocket"},
	["autobuz_licenta"]      = {"Licenta Sofer Autobuz", "Licenta Sofer Autobuz",        nil, 0.01, "pocket"},
	["petrolist_licenta"]    = {"Licenta Petrolist",     "Licenta Petrolist",            nil, 0.01, "pocket"},
	["pescar_licenta"]       = {"Licenta Pescar",        "Licenta Pescar",               nil, 0.01, "pocket"},
	["marinar_licenta"]      = {"Licenta Marinar",       "Licenta Marinar",              nil, 0.01, "pocket"},
	["licenta_parazit"]      = {"Licenta Deparazitare",  "Licenta Deparazitare",         nil, 0.01, "pocket"},
}

local function load_item_pack(name)
  local items = module("cfg/item/"..name)
  if items then
    for k,v in pairs(items) do
      cfg.items[k] = v
    end
  else
    print("[vRP] item pack ["..name.."] not found")
  end
end

load_item_pack("required")
load_item_pack("food")
load_item_pack("drugs")

return cfg
