RegisterNetEvent("Lucid:DiscordShow")
AddEventHandler("Lucid:DiscordShow",function(PlayerSvName,user_id,faction,oPlrs)
    SetDiscordAppId(1319629929561718784)
    SetDiscordRichPresenceAsset("logo")
    SetDiscordRichPresenceAssetText('Anubis Romania')
    SetDiscordRichPresenceAssetSmallText('discord.gg/anubisro')
    SetDiscordRichPresenceAction(0, "📰 Discord Server", "https://discord.gg/anubisro")
    SetDiscordRichPresenceAction(1, "🌐 Conecteaza-te", "fivem://connect/cfx.re/join/8775b3")
    SetRichPresence("Jucatori Online: "..oPlrs.."/64\n"..GetPlayerName(PlayerId()).." ["..user_id.."] - ["..faction.."]")
end)